version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: store_api
    ports:
      - "3307:3306"

  store-app:
    build: .
    container_name: store-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: BanuDawood@3006
    restart: always

