spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    #    url: jdbc:mysql://mysql:3306/store_api?createDatabaseIfNotExist=true
    #    used when we want to mysql inside docker
    username: root
    password: BanuDawood@3006
  jpa:
    show-sql: true
server:
  port: 8081
sonar:
  coverage:
    jacoco:
      xmlReportPaths: target/site/jacoco/jacoco.xml